### ISSUE TITLE
How do I run this demo?

### ISSUE THREAD

**Issue by kristianmandrup** [lgersman/enterjs2015-polymer_es6_demo#1]
Tried running `gulp` serve, then opened browser at `localhost:4000` but it just displays static serve root folder. Not very user friendly.

I see this in `serveTask.js`

``` js
  app
    .use(serveIndex(__dirname, {'icons': true}))
    .use(gzipStatic(__dirname))
    .listen(BROWSER_PORT)
  ;
```

So it look like it serves the root as static and I have to do this:

`http://localhost:4000/dist/hello-world/index.html`

However, then I get browser console errors trying to GET resource like:

`GET http://localhost:4000/dist/browser-polyfill.min.js`

From these includes... very strange!

``` html
    <script src="/dist/browser-polyfill.min.js"></script>
    <script src="/dist/webcomponents-lite.min.js"></script>
```

Then I tried serving from dist folder instead:

`.use(express.static(path.join(__dirname, 'dist')))`

and changing the script src paths:

``` html
    <script src="browser-polyfill.min.js"></script>
    <script src="webcomponents-lite.min.js"></script>
```

But then I get the error that it can't load the `.min.js` files, since `dist` only contains unminified assets...

Looking into the gulp file it looks as though it is configured to build and compile js into minified js files

`pfy(`find ${DIST} -name "_.js" -print | sed -rne 's:(._).js$:${BIN}/uglifyjs & -c -m > \1.min.js:p' | sh`)()`

If I change to regular `.js` files the next problem is that the bundle files don't make it to the `dist` folder either. Very strange!!

Oh, well... just curious. Any ideas/suggestions? 

Please add `install`, `test` and `run` instructions in the `README`.

Thanks :)

**Comment by lgersman** [comment]
Hi Kristian,

Hmm, worked for me (just checked my own code freshly out of Github to test it :-).

I added explanations to README.md : 
1. execute `npm serve` and open `http://localhost:4000` in your browser.
2. in your browser you will see the whole projectory listed. navigate to folder `dist`.
3. each example is separated in its own directory . navigate into the desired example directory and open `index.html` the see the example running in the browser.

**Comment by kristianmandrup** [comment]
I tried again following the steps you outlined. It is `gulp serve` not `npm serve`

Did you look at the browser console? Yes, it displays `hello world`, but in my case the minified assets are never generated and so it is unable to load any assets. 

I wonder if/how you manage to generate these assets? I wonder if it is due to me using Node 4.1 (for whatever reason) or just that you haven't verified your `dist` build?

**Comment by kristianmandrup** [comment]
I would love to have a more generic recipe for using ES2015 with Polymer, but your `build` task seems to be very complex/advanced and very particular to *nix systems. Would you help me build a more easy to understand, more portable build script that can customised by non OS experts ;)

I'd like to use this recipe, as proposed by @RobDodson himself

https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md

I'm running on Mac OSX. Maybe `sed` or `find` command is not working "correctly" or whatever other particulars that works in your OS system setup?

``` js
gulp.task('build', ['compile', 'test:node'], ()=>
  pfy(`find ${DIST} -name "*.js" -print | sed -rne 's:(.*).js$:${BIN}/uglifyjs & -c -m > \\1.min.js:p' | sh`)()
  .then(()=>new Promise((resolve, reject)=>{
        // append header to all javascript files
      gulp.src([`${DIST}/**/*.css`, `${DIST}/**/*.js`, `!${DIST}/*.js`])
      .pipe(through2.obj(
        (file, enc, cb)=>(file.contents=new Buffer(HEADER + file.contents)) && cb(null, file)
      ))
      .pipe(gulp.dest(DIST))
      .on('finish',resolve)
      .on('reject',reject)
    })
  )
  .then(
    pfy(`find ${DIST} \\( -name "*.min.js" -o -name "polymer*.html" \\) -print | sed -rne 's:(.*)$:gzip -9vc \\1 > \\1.gz:p' | sh`),
  )  
);
```

**Comment by lgersman** [comment]
> I tried again following the steps you outlined. It is gulp serve not npm serve

my mistake - it should be `npm run serve` (I just fixed it in README.md)

i just tried it using my default node version (v0.12.7) and even node 4.0 (`Now using node v4.0.0 (npm v2.14.2)`) - both worked fine for me.

I would guess (as you suggest) this is an OSX issue (i wrote the stuff using a debian linux environment. unfortunately i have no mac nor osx by hand :-)

You can try the shell snippets piece by piece in your OSX terminal to see whats going on. 
Take `find ${DIST} -name "*.js" -print | sed -rne 's:(.*).js$:${BIN}/uglifyjs & -c -m > \\1.min.js:p' | sh` for example (replace ${DIST} with just 'dist' !) and test it partially : 
1. is `find dist -name "*.js" -print` spitting out all js files in the dist folder or just nothing (which should not happen) ?
2. is `find dist -name "*.js" -print | sed -rne 's:(.*).js$:${BIN}/uglifyjs & -c -m > \\1.min.js:p'` spitting out the uglify commands to minize all js files found in the dist folder or just nothing (which should not happen) ? 

Check if the gulp 'prepare' task is copying the files correctly (i use the rsync command there ... dont know if that is available by default at osx ... ? )

Test manually if the 'prepare' task is working correctly on your machine : Execute in the checked out project folder : 
1. `cp node_modules/babel-core/browser-polyfill.js dist`
2. `cp bower_components/polymer/polymer*.html dist`
3. `cp bower_components/webcomponentsjs/webcomponents-lite.js dist`
4. `rsync -av --exclude '*.less' --exclude '*.es6' src/* dist`

Does one of the commands displaying an error message ?

keep me up to date with your progress.

**Comment by kristianmandrup** [comment]
Thanks, but I found some other simpler recipes. I now use starter-kit-plus
and even made my own generator for ES2015 using that template :)

**Comment by lgersman** [comment]
i agree that this project doesnt fit your environment (osx). 

and its also correct that my project is not a "starter kit" but a demo project :-)

>  Thanks, but I found some other simpler recipes.

... but _simpler_ might not really the right expression for project starter-kit-plus.

anyway - good luck !
